### ISSUE TITLE
密度表示モードでしか軸範囲の指定ができないのは仕様？

### ISSUE THREAD

**Issue by tmkawanabe** [digirea/ParallelCoordinate#1]

**Comment by tmkawanabe** [comment]
commit: 7be9b2ecbd527603aeb8b5b734ec5caa251b4159 では通常表示モードでも軸範囲選択が動作するようです

**Comment by doxas** [comment]
こちらは上記コミットにて不具合が解消しているようですので close してしまってよろしいでしょうか。
