### ISSUE TITLE
並行座標描画領域は固定？

### ISSUE THREAD

**Issue by tmkawanabe** [digirea/ParallelCoordinate#2]
ウィンドウサイズに応じて、あるいは任意に拡縮できるとよい
とくに軸の数が多い時は現在の固定幅状態では使いづらい

**Comment by uimac** [comment]
実装時のd3.parcoords.jsのリサイズ時に変更するとブラシが正常に動作しなくなるバグ
https://github.com/syntagmatic/parallel-coordinates/issues/76
が原因と思われます。
取り急ぎ、初回表示時のウィンドウサイズによって初期サイズを変更するようにしました。

最新のd3.parcoords.jsは差し替えただけではうまく動かなかったので調査中です.

**Comment by tmkawanabe** [comment]
初期サイズがウィンドウサイズに連動するようになったのは最新版で確認しました。
引き続き調査お願いします。

**Comment by doxas** [comment]
一度任意のデータ等を読み込んだあとでも、ウィンドウサイズに連動して描画領域が変化するような動作を実現できそうです。

ただし、ウィンドウサイズが変更した際に描画状態をリセットして再描画する必要があり、軸内で選択していた領域等が解除されてしまいます。選択状態を維持したままのウィンドウサイズ変更は仕組み上難しいようです。

**Comment by tmkawanabe** [comment]
@doxas ウィンドウサイズ連動動作の実装をお願いします。選択領域がリセットされることはマニュアルに記述してください。

**Comment by doxas** [comment]
ウィンドウサイズに連動するよう修正いたしました。マニュアルは別途、メールにて送付いたします。
