### ISSUE TITLE
軸の入れ替えを繰り返すと、軸番号の文字が傾いてくる

### ISSUE THREAD

**Issue by tmkawanabe** [digirea/ParallelCoordinate#3]
![2017-02-28 17 44 50](https://cloud.githubusercontent.com/assets/4436421/23397918/bf453520-fddd-11e6-82f6-6ff7b9cb04d7.png)

**Comment by tmkawanabe** [comment]
表示データは付属のres10000.csv

**Comment by doxas** [comment]
こちらは d3.parcoords.js の仕様のようで、軸タイトル部分でホイールスクロール操作を行うと、左右にタイトルラベルが傾くようになっているようです。
恐らく、タイトルラベルの文字数が多い場合に、傾けてやることで文字を読めるようにするための機能だと思われます。

**Comment by tmkawanabe** [comment]
ありがとうございます。了解です。クローズします。
