### ISSUE TITLE
軸の入れ替えを行うと、密度表示モードで描画されなくなる

### ISSUE THREAD

**Issue by tmkawanabe** [digirea/ParallelCoordinate#4]
![2017-02-28 17 47 51](https://cloud.githubusercontent.com/assets/4436421/23397986/0d142086-fdde-11e6-8fe1-37de45f75dc3.png)

表示データはres10000.csv

**Comment by doxas** [comment]
描画レイヤーが軸の入れ替え時に非表示になっているようですので、対応できないか調査してみます。

**Comment by tmkawanabe** [comment]
よろしくお願いします

**Comment by doxas** [comment]
軸の入れ替え時に、描画レイヤーが非表示にならないように修正いたしました。
