### ISSUE TITLE
単体版で「サンプリング数の選択」が出来ない

### ISSUE THREAD

**Issue by tmkawanabe** [digirea/ParallelCoordinate#6]
commit: 7be9b2ecbd527603aeb8b5b734ec5caa251b4159

**Comment by tmkawanabe** [comment]
これは現バージョンではサンプリングしない（全数描画する）という仕様になったんでしたっけ？
（であればクローズしていただいて結構です）

**Comment by doxas** [comment]
ダウンサンプリングは、単体版では非対応となっております。

**Comment by tmkawanabe** [comment]
@doxas 　こちらユーザ向け利用説明書では単体版でもサンプリング数が設定可能とされています。（例：4.2.3節）　仕様書のアップデートをお願いできますでしょうか。

**Comment by doxas** [comment]
@tmkawanabe かしこまりました。アップデートした PDF ファイルはメール等でお送りする形で問題ございませんでしょうか。

**Comment by tmkawanabe** [comment]
@doxas はい、pdfとTeXソースをメールでお送りください。よろしくお願いいたします。

**Comment by doxas** [comment]
@tmkawanabe 申し訳ありません、ちょっと説明の仕方に語弊がありましたので、念のため確認させていただきたいのですが、このサンプリングという機能自体が *.sph という拡張子のファイルの場合だけ有効になるようになっています。
CSV ファイルが対象の場合はダウンサンプリングはせず、全数描画するような形です。

上記を踏まえ、マニュアルに「サンプリング機能は CSV ファイルには対応しません」といった文言を追加する形で問題ございませんでしょうか。また、このバージョンの納品時には TeX を一緒に納品しておらず PDF を直接アーカイブしてお送りしていたようです。マニュアルの作成に TeX ファイルを利用しておりませんので PDF の直接編集という形になります。

**Comment by tmkawanabe** [comment]
@doxas 記述内容についてはそれでお願いします。TeXソースではないとのことですが、元データはWordでしょうか？でしたらそちらもお送りください。（ユーザマニュアル類のmarkdown化を検討しています）
