### ISSUE TITLE
選択範囲の強調表示に、軸間での連続性のない所がある

### ISSUE THREAD

**Issue by tmkawanabe** [digirea/ParallelCoordinate#7]
添付図の suger軸とfat軸間で顕著
データはサンプルデータのnuts.csv

![2017-03-01 15 14 30](https://cloud.githubusercontent.com/assets/4436421/23448384/015b7300-fe94-11e6-9025-13a3128a9b82.jpg)
commit: 7be9b2ecbd527603aeb8b5b734ec5caa251b4159

**Comment by doxas** [comment]
こちらの現象が起こるのは、log scale モードで描画を行っている場合です。
対数軸での表示ですと、値が 0 になるもの（上記画像で言いますとビタミンC）が範囲外に設定されてしまいますので、そこで消失した分のラインが消えてしまうようです。

**Comment by tmkawanabe** [comment]
了解です。データにゼロあるいは負数を含む時に対数表示を選択した場合、警告メッセージを表示することは可能でしょうか。

**Comment by doxas** [comment]
対数表示を行った際に、ゼロ以下のデータが存在する場合にアラートを出し、利用者に注意をうながすようにしてみます。

**Comment by doxas** [comment]
該当データが存在する場合、log scale のチェックボックスを ON にした際に、アラートを表示するようにいたしました。
